### ISSUE TITLE
err

### ISSUE THREAD

**Issue by NiceDayZc** [glizzykingdreko/Glizzy-TLS#1]
subprocess.CalledProcessError: Command '['go', 'build', '-o', 'libtls_client.so', '-buildmode=c-shared', 'tls_client.go']' returned non-zero exit status 1.

**Comment by glizzykingdreko** [comment]
Can you tell me more about the OS you are using? Keep in mind that this project has been crated as a first test/implementation just to have a way to let me send a TLS GET request from my raspberry py in python (since tls-client didn't support it)
